// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import robot.Robot;

/**
 *
 */
public class LEDSeq1Cmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    private Timer LEDSeqTimer;


    public LEDSeq1Cmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lighting);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        LEDSeqTimer = new Timer();
        LEDSeqTimer.start();  
        //Robot.lighting.SetLEDMthd(0.87);
        //Robot.lighting.SetLEDMthd(0.71);
        }
    

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if(LEDSeqTimer.get() <2){
            Robot.lighting.SetLEDMthd(0.61);
        }
        else if(LEDSeqTimer.get() <4){
            Robot.lighting.SetLEDMthd(0.87);
        }
        else if (LEDSeqTimer.get() <6){
            Robot.lighting.SetLEDMthd(0.71);
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if(LEDSeqTimer.get() >6){
            Robot.lighting.SetLEDMthd(0.99);
            System.out.println("Timer excess 6");
            return true;
        }

        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.lighting.LEDOff();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
